apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: frontend
  name: frontend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: frontend
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
      - image: shumila/prak6
        imagePullPolicy: Always
        name: frontend
        env:
        - name: JOURNAL_ENTRIES  
          valueFrom:
            configMapKeyRef:
              name: app-config   
              key: journalEntries 
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
